<a href="https://www.kaggle.com/code/ahmedfakhar123/phase-3-numpy-in-real-world-scenarios?scriptVersionId=316055092" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

<div align="center">

<img src="https://capsule-render.vercel.app/api?type=rect&color=gradient&text=%20%20Phase%203%20%20&fontAlign=30&fontSize=30&textBg=true&desc=Real-World%20NumPy%20Practice%20🌍⚡&descAlign=65&descAlignY=50)">

</div>

---

## ⚙️ Importing Required Libraries: NumPy & Matplotlib

In [1]:
import numpy as np
import matplotlib.pyplot as plt

---

## 📊 Sample Dataset — Restaurant Sales Over Years 🍽️💰

Let’s work with a small but realistic dataset in NumPy to simulate **business sales analysis** 📈.

Each row represents a **restaurant**, and each column stores its **annual revenue**:

**Structure:**
`[restaurant_id, 2021, 2022, 2023, 2024, 2025]`

### 🔹 Dataset

In [2]:
sales_data = np.array([
    [1, 150000, 175000, 140000, 210000, 300000],  # Spice Hub 🌶️
    [2, 120000, 140000, 155000, 180000, 260000],  # Urban Bites 🍔
    [3, 200000, 190000, 210000, 270000, 350000],  # Royal Dine 👑
    [4, 100000, 130000, 125000, 160000, 240000],  # Food Corner 🍕
    [5, 270000, 190000, 280000, 250000, 320000]   # Grill Master 🔥
])

---

## Resturant sales analysis
now we are analysing data of different resturants

### Shape of data
first we have to identify matrix/data shape

In [3]:
print(f"Sales Data shape: {sales_data.shape}")

Sales Data shape: (5, 6)


### Analysing data of first 3 resturants
We have to figure out what are the sales of 1st three resturants in five years

In [4]:
print(f"\nSample data for 1st three resturants:\n {sales_data[:3]}")

# If we don't want resturant_id then
print(f"\nSample data for 1st three resturants:\n {sales_data[:, 1:]}")


Sample data for 1st three resturants:
 [[     1 150000 175000 140000 210000 300000]
 [     2 120000 140000 155000 180000 260000]
 [     3 200000 190000 210000 270000 350000]]

Sample data for 1st three resturants:
 [[150000 175000 140000 210000 300000]
 [120000 140000 155000 180000 260000]
 [200000 190000 210000 270000 350000]
 [100000 130000 125000 160000 240000]
 [270000 190000 280000 250000 320000]]


### Total sales of each resturant
Now we come to know how to analyze data, now we are to find the total sales of each resturant over all years

In [5]:
print(f"Total sales of 1st resturant: {np.sum(sales_data[0, 1:])}")
print(f"Total sales of 2st resturant: {np.sum(sales_data[1, 1:])}")
print(f"Total sales of 3st resturant: {np.sum(sales_data[2, 1:])}")
print(f"Total sales of 4st resturant: {np.sum(sales_data[3, 1:])}")
print(f"Total sales of 5st resturant: {np.sum(sales_data[4, 1:])}")

Total sales of 1st resturant: 975000
Total sales of 2st resturant: 855000
Total sales of 3st resturant: 1220000
Total sales of 4st resturant: 755000
Total sales of 5st resturant: 1310000


### Total sales per year
Now we are finding total sales of all resturants per year

In [6]:
yearly_total = np.sum(sales_data[:, 1:], axis=0)
print(f"Yearly total sales: {yearly_total}")

Yearly total sales: [ 840000  825000  910000 1070000 1470000]


### Overall sales of all resturants
We have to calculate all sales over five years of all resturants together

In [7]:
overall_total = np.sum(yearly_total)
print(f"Overall total sales: {overall_total}")

Overall total sales: 5115000


### Minimum sales per resturant
Finding which is the minimum sales for each resturant

In [8]:
min_sales = np.min(sales_data[:, 1:], axis=1)
print(f"Minimum sales per resturant: {min_sales}")

Minimum sales per resturant: [140000 120000 190000 100000 190000]


### Maximum sales per year
Finding the maximum sales in each year

In [9]:
max_sales = np.max(sales_data[:, 1:], axis=0)
print(f"Maximum sales per year: {max_sales}")

Maximum sales per year: [270000 190000 280000 270000 350000]


### Average sales per resturant

In [10]:
avg_sales = np.mean(sales_data[:, 1:], axis=1)
print(f"Average sales per resturant: {avg_sales}")

Average sales per resturant: [195000. 171000. 244000. 151000. 262000.]
