<a href="https://www.kaggle.com/code/ahmedfakhar123/phase-1-numpy-foundation-creation-of-arrays-etc?scriptVersionId=314278747" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# NumPy for AI: Phase 1 — Arrays, Performance & Core Operations

NumPy (short for **Numerical Python**) is a fundamental Python library used for **numerical computing**. It provides powerful tools for working with arrays, mathematical functions, and linear algebra—making it essential for data science, machine learning, and scientific computing.

---

## 🔹 What is NumPy?

NumPy is a library that allows you to work with **large, multi-dimensional arrays and matrices**, along with a collection of mathematical functions to operate on them efficiently.

---

## 🔹 Why use NumPy?

Compared to Python lists, NumPy arrays are:

* **Faster** (optimized in C under the hood)
* **More memory-efficient**
* Support **vectorized operations** (no need for loops)

---

## 🔹 Where NumPy is Used

* Data Science (Pandas, SciPy depend on it)
* Machine Learning (TensorFlow, PyTorch)
* Image Processing
* Scientific simulations

---

## Importing numpy library

In [1]:
import numpy as np

## Creating arrays from list

In [2]:
# 1D array (vector)
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array (vector):", arr_1d)

# 2D array (matrix)
arr_2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
print("\n2D array (matrix):\n", arr_2d)

1D array (vector): [1 2 3 4 5]

2D array (matrix):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Multiplication in numpy arrays

In [3]:
py_list = [1, 2, 3]
print("Python list multiplication:", py_list * 2) # Duplicates all list entries

np_arr = np.array([1, 2, 3])
print("Python list multiplication:", np_arr * 2) # Element-wise multiplication

Python list multiplication: [1, 2, 3, 1, 2, 3]
Python list multiplication: [2 4 6]


## Performance Comparison (numpy array VS python list)

In [4]:
import time

# Python list (loop-based computation)
start = time.time()
py_list = [i * 2 for i in range(10_000_000)]
print("Python list operation time:", time.time() - start)

# NumPy array (vectorized computation)
start = time.time()
np_arr = np.arange(10_000_000) * 2
print("NumPy array operation time:", time.time() - start)

Python list operation time: 0.7386419773101807
NumPy array operation time: 0.043905019760131836


## Array Creation Methods

In [5]:
# Zero matrix (all elements = 0)
zeros = np.zeros((3, 3))
print("\nZero matrix:\n", zeros)

# Ones matrix (all elements = 1)
ones = np.ones((5, 4))
print("\nOnes matrix:\n", ones)

# Constant matrix (all elements = 9)
full = np.full((3, 4), 9)
print("\nConstant matrix (value = 9):\n", full)

# Random matrix (values between 0 and 1)
random_matrix = np.random.random((3, 5))
print("\nRandom matrix:\n", random_matrix)

# Sequence array (start=0, stop=10, step=2)
sequence = np.arange(0, 10, 2)
print("\nSequence array:\n", sequence)


Zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Constant matrix (value = 9):
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]

Random matrix:
 [[0.34685194 0.8807921  0.59831823 0.81085216 0.62533846]
 [0.50578219 0.2355833  0.30963965 0.35102914 0.25414867]
 [0.08716927 0.32267905 0.48803321 0.2426803  0.45002519]]

Sequence array:
 [0 2 4 6 8]


## Array Types (Dimensions)

In [6]:
# 1D array (vector)
vector = np.array([1, 2, 3, 4, 5])
#print("\nVector (1D array):", vector)

# 2D array (matrix)
matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
print("\nMatrix (2D array):\n", matrix)

# 3D array (tensor)
tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("\nTensor (3D array):\n", tensor)


Matrix (2D array):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Tensor (3D array):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [7]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

# Shape: (rows, columns)
#print("\nShape:", arr.shape)

# Total number of elements
#print("Size:", arr.size)

# Number of dimensions
#print("Dimensions:", arr.ndim)

# Data type of elements
#print("Data type:", arr.dtype)

## Array reshaping

In [8]:
# Create a 1D array with values from 0 to 11
arr = np.arange(12)
#print("\nOriginal array:", arr)

# Reshape into a 3x4 matrix (rows=3, columns=4)
reshaped = arr.reshape(3, 4)
#print("\nReshaped array (3x4):\n", reshaped)

# Flatten: returns a NEW 1D copy of the array
flattened = reshaped.flatten()
#print("\nFlattened array (copy):", flattened)

# Ravel: returns a VIEW when possible (more memory-efficient)
raveled = reshaped.ravel()
#print("\nRaveled array (view if possible):", raveled)

# Transpose: swap rows and columns (shape becomes 4x3)
transposed = reshaped.T
#print("\nTransposed array (4x3):\n", transposed)