<a href="https://www.kaggle.com/code/ahmedfakhar123/phase-1-numpy-foundation-creation-of-arrays-etc?scriptVersionId=315595272" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

<div align="center">

<img src="https://capsule-render.vercel.app/api?type=rect&color=gradient&text=NumPy%20for%20AI&fontAlign=25&fontSize=30&textBg=true&desc=Phase%201%20-%20Arrays,%20Performance%20and%20Core%20Operations&descAlign=70&descAlignY=50" />

</div>

NumPy (Numerical Python) is the backbone of the Python Data Science ecosystem 🌐. It provides the high-performance multidimensional array objects and tools for working with them that make libraries like Pandas 📊, Scikit-Learn 🤖, and TensorFlow 🧠 possible.

<div align="center">
    
<img src="https://img.shields.io/badge/Vectorization-0EA5E9?style=for-the-badge" />
<img src="https://img.shields.io/badge/Broadcasting-6366F1?style=for-the-badge" />
<img src="https://img.shields.io/badge/Memory%20Optimization-22C55E?style=for-the-badge" />
<img src="https://img.shields.io/badge/Array%20Manipulation-F59E0B?style=for-the-badge" />
<img src="https://img.shields.io/badge/Linear%20Algebra-E11D48?style=for-the-badge" />

</div>

<p align="center">
  <img src="https://itsmybot.com/wp-content/uploads/2025/07/cmbjnvfqueifpmhedgjv.png" width="400">
  &nbsp;&nbsp;&nbsp;
  <img src="https://content-media-cdn.codefinity.com/courses/4f4826d5-e2f8-4ffd-9fd0-6f513353d70a/section-1/applications_numpy.png" width="600">
</p>

---


<div align="center">

<img src="https://capsule-render.vercel.app/api?type=venom&height=150&text=1.%20Introduction%20to%20NumPy&fontSize=45&color=0:8871e5,100:b678c4&stroke=b678c4" />

</div>

### What is NumPy? 🔍
NumPy 🔢 is a library that allows you to work with large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on them efficiently.

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMrTWz33b86nfIrgaW9jE_t-7VCcqJtjL-pg&s" width=300 >


### Why NumPy over Python Lists?
 * **⏱️ Performance:** NumPy arrays are stored in contiguous memory blocks, making them significantly faster than Python's lists (which are arrays of pointers).
    <img src="https://miro.medium.com/v2/resize:fit:1400/0*bX7RWHxj1IqoUthB.png" width=400 >

 * **🧮 Vectorization:** It allows for "element-wise" operations without the need for explicit for loops.
    <img src="https://www.scaler.com/topics/images/np-vectorize-thumbnail.webp" width=400 >

 * **📊 Broadcasting:** A powerful mechanism that allows NumPy to work with arrays of different shapes during arithmetic operations.
    <img src="https://miro.medium.com/v2/resize:fit:1400/1*hhxACowyGdVj2fcC6_KXZg.png" width=400 >

<div align="center">

<img src="https://capsule-render.vercel.app/api?type=venom&height=150&text=2.%20Environment%20Setup,%20%20Basic%20Creation&fontSize=45&color=0:8871e5,100:b678c4&stroke=b678c4" />

</div>

The standard convention is to import NumPy under the alias np.

In [1]:
import numpy as np

# Creating basic 1D and 2D structures
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(f"1D Vector:\n{arr_1d}")
print(f"\n2D Matrix:\n{arr_2d}")

1D Vector:
[1 2 3 4 5]

2D Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


<div align="center">

<img src="https://capsule-render.vercel.app/api?type=venom&height=150&text=3.%20The%20Power%20of%20Vectorization&fontSize=45&color=0:8871e5,100:b678c4&stroke=b678c4" />

</div>
One of the most critical concepts in NumPy is **Vectorization**. In standard Python, multiplying a list by a scalar duplicates the list. In NumPy, it performs a mathematical operation on every individual element.

In [2]:
py_list = [1, 2, 3]
np_arr = np.array([1, 2, 3])

print(f"Python List Multiplication (Duplication): {py_list * 2}")
print(f"NumPy Array Multiplication (Element-wise): {np_arr * 2}")

Python List Multiplication (Duplication): [1, 2, 3, 1, 2, 3]
NumPy Array Multiplication (Element-wise): [2 4 6]


### Performance Benchmark
To understand why NumPy is used in AI, we compare the time taken to process 10 million elements.

In [3]:
import time

size = 10_000_000

# Python List approach
start = time.time()
py_list = [i * 2 for i in range(size)]
print(f"Python List time: {time.time() - start:.4f}s")

# NumPy Vectorized approach
start = time.time()
np_arr = np.arange(size) * 2
print(f"NumPy Array time:  {time.time() - start:.4f}s")

Python List time: 0.7932s
NumPy Array time:  0.0447s


<div align="center">

<img src="https://capsule-render.vercel.app/api?type=venom&height=150&text=4.%20Advanced%20Array%20Initialization&fontSize=45&color=0:8871e5,100:b678c4&stroke=b678c4" />

</div>

Beyond manual lists, NumPy provides optimized functions to create specific types of matrices used frequently in Machine Learning (e.g., Weight initialization).

| Method | Description | Use Case |
|---|---|---|
| np.zeros() | Fills array with 0.0 | Bias initialization |
| np.ones() | Fills array with 1.0 | Masking |
| np.full() | Fills array with a constant | Custom initial values |
| np.random.random() | Random values [0, 1] | Weight initialization |
| np.arange() | Range of values with steps | Creating indices |

In [4]:
# Zero matrix (all elements = 0)
zeros = np.zeros((3, 3))
print("\nZero matrix:\n", zeros)

# Ones matrix (all elements = 1)
ones = np.ones((5, 4))
print("\nOnes matrix:\n", ones)

# Constant matrix (all elements = 9)
full = np.full((3, 4), 9)
print("\nConstant matrix (value = 9):\n", full)

# Random matrix (values between 0 and 1)
random_matrix = np.random.random((3, 5))
print("\nRandom matrix:\n", random_matrix)

# Sequence array (start=0, stop=10, step=2)
sequence = np.arange(0, 10, 2)
print("\nSequence array:\n", sequence)


Zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Constant matrix (value = 9):
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]

Random matrix:
 [[0.72092434 0.7214431  0.08721488 0.08879594 0.28413521]
 [0.83946484 0.44230004 0.14831715 0.98606406 0.61852376]
 [0.54235225 0.10762108 0.47700722 0.36079333 0.7473533 ]]

Sequence array:
 [0 2 4 6 8]


<div align="center">

<img src="https://capsule-render.vercel.app/api?type=venom&height=150&text=5.%20Array%20Dimensions,%20Anatomy&fontSize=45&color=0:8871e5,100:b678c4&stroke=b678c4" />

</div>

Understanding the "Shape" and "Rank" of an array is vital for debugging Neural Network layers.
 * **Scalar:** 0D (A single number)
 * **Vector:** 1D (Rank 1 tensor)
 * **Matrix:** 2D (Rank 2 tensor)
 * **Tensor:** 3D+ (Rank 3+ tensor)

<img src="https://perso.esiee.fr/~chierchg/optimization/_images/arrays.png" width=500 >

In [5]:
# 1D array (vector)
vector = np.array([1, 2, 3, 4, 5])
#print("\nVector (1D array):", vector)

# 2D array (matrix)
matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
#print("\nMatrix (2D array):\n", matrix)

# 3D array (tensor)
tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
#print("\nTensor (3D array):\n", tensor)

## Array Properties

In [6]:
# Inspecting Properties
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Shape (Rows, Cols): {arr.shape}")
print(f"Dimensions (Rank):  {arr.ndim}")
print(f"Total Elements:     {arr.size}")
print(f"Data Type:          {arr.dtype}")

Shape (Rows, Cols): (2, 3)
Dimensions (Rank):  2
Total Elements:     6
Data Type:          int64


<div align="center">

<img src="https://capsule-render.vercel.app/api?type=venom&height=150&text=6.%20Structural%20Manipulation%20(Reshaping)&fontSize=45&color=0:8871e5,100:b678c4&stroke=b678c4" />

</div>

Data often arrives in a flat format and needs to be reshaped for processing.
> **Note:** flatten() creates a deep copy (new memory), while ravel() creates a "view" (more memory-efficient) whenever possible.
>
<img src="https://miro.medium.com/v2/1*lFZzE9PgKTRR8jlFI4EUtw.png" width=900 > 

In [7]:
# 1. Reshape 1D (12 elements) to 3x4 Matrix
arr = np.arange(12)
reshaped = arr.reshape(3, 4)

# 2. Transpose (Swap axes)
transposed = reshaped.T

# 3. Flatten back to 1D
flat = reshaped.flatten()

print(f"Original:\n{arr}")
print(f"\n3x4 Matrix:\n{reshaped}")
print(f"\nTransposed (4x3):\n{transposed}")

Original:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

3x4 Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Transposed (4x3):
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


---

<div align="center">

<img src="https://capsule-render.vercel.app/api?type=venom&height=150&text=7.%20Real-World%20Applications%20of%20NumPy&fontSize=45&color=0:8871e5,100:b678c4&stroke=b678c4" />

</div>
<br>
<img src="https://media.licdn.com/dms/image/v2/D4D22AQFxNaiA5LvV5g/feedshare-shrink_800/B4DZh_q6VZHsAg-/0/1754488613074?e=2147483647&v=beta&t=rA1d3NC6Z1RwWMO0_mO4Tsj_QtRyJehKB_jvP_D0uMw" width=600 >

NumPy isn't just for math homework; it is the engine under the hood of almost every major scientific field:

* **Machine Learning & Deep Learning:** Neural networks represent weights and biases as NumPy arrays. Concepts like **Backpropagation** rely heavily on matrix multiplication and transposing. 🧠
* **Image Processing:** Digital images are essentially 3D NumPy arrays (Height x Width x RGB Channels). Operations like cropping or grayscaling are just array slicing and math. 📸
* **Signal Processing:** NumPy is used to handle sound waves and radio frequencies by representing them as discrete numerical sequences for Fourier Transforms. 📡
* **Finance & Statistics:** Analysts use NumPy for Monte Carlo simulations and risk assessment, processing millions of data points with vectorized operations. 📈


---

<div align="center">

<img src="https://capsule-render.vercel.app/api?type=venom&height=150&text=8.%20Summary%20of%20Phase%201&fontSize=45&color=0:8871e5,100:b678c4&stroke=b678c4" />

</div>

In this introductory phase, we moved from the basics of array creation to understanding the core mechanics that make NumPy superior to standard Python lists.

**Key Takeaways:**
1.  **Efficiency:** Use NumPy for large datasets to save memory and time. ⚡
2.  **Vectorization:** Avoid `for` loops whenever possible; use element-wise operations. 🔄
3.  **Shapes Matter:** Always keep track of your `shape` and `ndim`—this is where 90% of debugging happens in AI. 📐


---

<div align="center">

<img src="https://capsule-render.vercel.app/api?type=venom&height=150&text=Conclusion:%20The%20First%20Step%20into%20AI&fontSize=45&color=0:8871e5,100:b678c4&stroke=b678c4" />

</div>

Mastering NumPy is the "Hello World" of Data Science. By understanding how to manipulate arrays, reshape data, and leverage vectorized performance, you have built the foundation necessary to explore **Pandas** for data manipulation and **Matplotlib** for visualization.

Next in **Phase 2**, we will dive into **Indexing, Slicing, and Broadcasting**—the techniques that allow us to extract and manipulate specific data features with surgical precision! 🎯

---

**Happy Coding!** 💻✨

---

<div align="center">

<img src="https://capsule-render.vercel.app/api?type=venom&height=150&text=Support&fontSize=45&color=0:8871e5,100:b678c4&stroke=b678c4" />

</div>

- 🔼 Upvote the notebook  
- 📢 Share it  
- 🧠 Follow for more AI content  

---